# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sterm', models.CharField(max_length=255)),
                ('AppId', models.BigIntegerField()),
                ('AppName', models.CharField(max_length=255)),
                ('AppDeveloper', models.CharField(max_length=255)),
                ('DevEmail', models.EmailField(max_length=254)),
                ('IconURL', models.URLField()),
            ],
        ),
    ]
