# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0002_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='AppId',
            field=models.CharField(max_length=255),
        ),
    ]
