# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0004_auto_20171010_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='s_id',
            new_name='queryresult',
        ),
    ]
