# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0005_auto_20171010_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sterm', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='app',
            name='sterm',
        ),
        migrations.AlterField(
            model_name='queryresult',
            name='link',
            field=models.URLField(max_length=255),
        ),
        migrations.AddField(
            model_name='appquery',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pstore.App'),
        ),
    ]
